name: build and test

on:
  pull_request:
    branches: [ develop ]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup SonarQube
        run: |
           echo "sonar.host.url= ${{ secrets.SONAR_HOST_URL }}" >> $GITHUB_ENV
           echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Unit Tests
        run: dotnet test --logger trx --results-directory ./TestResults --configuration Release

      - name: Run SonarScanner
        run: .sonar/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=Inventofree \
          -Dsonar.sources=. \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload SonarQube report
        uses: actions/upload-artifact@v2
        with:
          name: sonarqube-report
          path: .sonarqube/out/sonar-report.json

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: TestResults/*.trx